#!/usr/bin/env python3
"""
Prompts and Queries Index

Import tất cả các prompts và queries từ các file con
"""

# Neo4j Queries
from .neo4j_queries import (
    VALIDATE_DOCUMENT_QUERY,
    LANGUAGE_DETECTION_SCOPED_QUERY,
    LANGUAGE_DETECTION_GLOBAL_QUERY,
    HYBRID_SEARCH_SCOPED_QUERY,
    HYBRID_SEARCH_GLOBAL_QUERY,
    PARENT_CONTENT_QUERY,
    RELATED_CONTENT_QUERY,
    SEMANTIC_SEARCH_SCOPED_QUERY,
    SEMANTIC_SEARCH_GLOBAL_QUERY
)

# All Prompt Templates
from .prompts import (
    LANGUAGE_DETECTION_PROMPT,
    TRANSLATION_PROMPT,
    KEYWORD_EXTRACTION_PROMPT,
    ANSWER_GENERATION_PROMPT
)

__all__ = [
    # Queries
    'VALIDATE_DOCUMENT_QUERY',
    'LANGUAGE_DETECTION_SCOPED_QUERY',
    'LANGUAGE_DETECTION_GLOBAL_QUERY',
    'HYBRID_SEARCH_SCOPED_QUERY',
    'HYBRID_SEARCH_GLOBAL_QUERY',
    'PARENT_CONTENT_QUERY',
    'RELATED_CONTENT_QUERY',
    'SEMANTIC_SEARCH_SCOPED_QUERY',
    'SEMANTIC_SEARCH_GLOBAL_QUERY',
    
    # Prompt Templates
    'LANGUAGE_DETECTION_PROMPT',
    'TRANSLATION_PROMPT',
    'KEYWORD_EXTRACTION_PROMPT',
    'ANSWER_GENERATION_PROMPT'
]